# Pre-commit hooks for repo.

# Packages:
#   pre-commit: General pre-commits for formatting.
#   black: Python code strict formatting.
#   pyupgrade:  Upgrade syntax for newer versions of the language.
#   isort: Sorts imports.
#   flake8: Checks code follows PEP8 standard.
#   mypy: Static typing.
#   conventional-pre-commit: commit format checker.
#   blacken-docs: Checks docs follow black format standard.
#   pydocstyle: Checking docstring style.

default_stages: [commit]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude_types: [image]
      - id: check-merge-conflict
      - id: debug-statements
      - id: mixed-line-ending
      - id: check-yaml

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        exclude_types: [image]

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.10.0
    hooks:
      - id: pyupgrade

  - repo: https://github.com/timothycrosley/isort
    rev: 5.7.0
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
      - id: flake8
        args: ['--max-line-length=89', '--extend-ignore=E203,BLK100', '--exclude=unit_tests']

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.931
    hooks:
      - id: mypy
        exclude: ^docs/
        args: [--config-file=mypy.ini]

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v1.2.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]


  - repo: https://github.com/asottile/blacken-docs
    rev: v1.8.0
    hooks:
      - id: blacken-docs
        additional_dependencies: [black==20.8b1]
