# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        sudo apt-get install -y libsdl1.2-dev libsdl-image1.2-dev libsdl-mixer1.2-dev libsdl-ttf2.0-dev
        sudo apt-get update
        sudo apt-get install -qqy x11-apps
        sudo apt install xorg-dev libx11-dev libgl1-mesa-glx

        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Lint with black and flake8 and mypy
      run: |
        # Run the pre-commit hooks on all files
        pre-commit run --all-files
    - name: Test with pytest
      run: |


        pytest
